//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Frontpage</summary>
	[PublishedContentModel("frontpage")]
	public partial class Frontpage : Master
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "frontpage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Frontpage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Frontpage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About me description
		///</summary>
		[ImplementPropertyType("aboutMeDescription")]
		public string AboutMeDescription
		{
			get { return this.GetPropertyValue<string>("aboutMeDescription"); }
		}

		///<summary>
		/// About me image
		///</summary>
		[ImplementPropertyType("aboutMeImage")]
		public IPublishedContent AboutMeImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutMeImage"); }
		}

		///<summary>
		/// About me link
		///</summary>
		[ImplementPropertyType("aboutMeLink")]
		public IPublishedContent AboutMeLink
		{
			get { return this.GetPropertyValue<IPublishedContent>("aboutMeLink"); }
		}

		///<summary>
		/// Copyright name
		///</summary>
		[ImplementPropertyType("copyrightName")]
		public string CopyrightName
		{
			get { return this.GetPropertyValue<string>("copyrightName"); }
		}

		///<summary>
		/// Facebook link
		///</summary>
		[ImplementPropertyType("facebookLink")]
		public string FacebookLink
		{
			get { return this.GetPropertyValue<string>("facebookLink"); }
		}

		///<summary>
		/// Google Analytics id
		///</summary>
		[ImplementPropertyType("googleAnalyticsId")]
		public string GoogleAnalyticsId
		{
			get { return this.GetPropertyValue<string>("googleAnalyticsId"); }
		}

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("header")]
		public string Header
		{
			get { return this.GetPropertyValue<string>("header"); }
		}

		///<summary>
		/// Instagram link
		///</summary>
		[ImplementPropertyType("instagramLink")]
		public string InstagramLink
		{
			get { return this.GetPropertyValue<string>("instagramLink"); }
		}

		///<summary>
		/// LightwidgetId: Id from lightwidget for the instagram feed
		///</summary>
		[ImplementPropertyType("lightwidgetId")]
		public string LightwidgetId
		{
			get { return this.GetPropertyValue<string>("lightwidgetId"); }
		}

		///<summary>
		/// OG Site Name
		///</summary>
		[ImplementPropertyType("oGSiteName")]
		public string OGsiteName
		{
			get { return this.GetPropertyValue<string>("oGSiteName"); }
		}

		///<summary>
		/// Sub header
		///</summary>
		[ImplementPropertyType("subHeader")]
		public string SubHeader
		{
			get { return this.GetPropertyValue<string>("subHeader"); }
		}

		///<summary>
		/// Twitter Handle
		///</summary>
		[ImplementPropertyType("twitterHandle")]
		public string TwitterHandle
		{
			get { return this.GetPropertyValue<string>("twitterHandle"); }
		}

		///<summary>
		/// Youtube link
		///</summary>
		[ImplementPropertyType("youtubeLink")]
		public string YoutubeLink
		{
			get { return this.GetPropertyValue<string>("youtubeLink"); }
		}
	}
}
